-- Orders table
CREATE TABLE IF NOT EXISTS orders (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    uuid VARCHAR(36) NOT NULL,
    user_id BIGINT UNSIGNED NOT NULL,
    slug VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    ip_address VARCHAR(45) NOT NULL,
    currency_code VARCHAR(3) NOT NULL,
    currency_rate DECIMAL(10, 2) NOT NULL DEFAULT 1.00,
    payment_method VARCHAR(50) NOT NULL,
    payment_status VARCHAR(50) NOT NULL,
    fulfillment_type VARCHAR(50) NOT NULL,
    is_rush_order BOOLEAN NULL,
    estimated_delivery_time INT NULL,
    delivery_time_slot_id BIGINT UNSIGNED NULL,
    delivery_boy_id BIGINT UNSIGNED NULL,
    delivery_zone_id BIGINT UNSIGNED NULL,
    wallet_balance DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
    promo_code VARCHAR(50) NULL,
    promo_discount DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
    gift_card VARCHAR(50) NULL,
    gift_card_discount DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
    delivery_charge DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
    handling_charges DECIMAL(10, 2) NULL,
    per_store_drop_off_fee DECIMAL(10, 2) NULL,
    subtotal DECIMAL(10, 2) NOT NULL,
    total_payable DECIMAL(10, 2) NOT NULL,
    final_total DECIMAL(10, 2) NOT NULL,
    status VARCHAR(50) NULL,
    billing_name VARCHAR(255) NOT NULL,
    billing_address_1 VARCHAR(255) NOT NULL,
    billing_address_2 VARCHAR(255) NULL,
    billing_landmark VARCHAR(255) NOT NULL,
    billing_zip VARCHAR(20) NOT NULL,
    billing_phone VARCHAR(20) NOT NULL,
    billing_address_type VARCHAR(50) NOT NULL,
    billing_latitude DECIMAL(10, 8) NOT NULL,
    billing_longitude DECIMAL(11, 8) NOT NULL,
    billing_city VARCHAR(100) NOT NULL,
    billing_state VARCHAR(100) NOT NULL,
    billing_country VARCHAR(100) NOT NULL,
    billing_country_code VARCHAR(3) NOT NULL,
    shipping_name VARCHAR(255) NOT NULL,
    shipping_address_1 VARCHAR(255) NOT NULL,
    shipping_address_2 VARCHAR(255) NULL,
    shipping_landmark VARCHAR(255) NOT NULL,
    shipping_zip VARCHAR(20) NOT NULL,
    shipping_phone VARCHAR(20) NOT NULL,
    shipping_address_type VARCHAR(50) NOT NULL,
    shipping_latitude DECIMAL(10, 8) NOT NULL,
    shipping_longitude DECIMAL(11, 8) NOT NULL,
    shipping_city VARCHAR(100) NOT NULL,
    shipping_state VARCHAR(100) NOT NULL,
    shipping_country VARCHAR(100) NOT NULL,
    shipping_country_code VARCHAR(3) NOT NULL,
    order_note TEXT NULL,
    created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Order Items table
CREATE TABLE IF NOT EXISTS order_items (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    order_id BIGINT UNSIGNED NOT NULL,
    product_id BIGINT UNSIGNED NOT NULL,
    product_variant_id BIGINT UNSIGNED NOT NULL,
    store_id BIGINT UNSIGNED NOT NULL,
    title VARCHAR(255) NOT NULL,
    variant_title VARCHAR(255) NOT NULL,
    gift_card_discount DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
    admin_commission_amount DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
    seller_commission_amount DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
    commission_settled VARCHAR(1) NOT NULL DEFAULT '0',
    discounted_price DECIMAL(10, 2) NOT NULL,
    discount DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
    tax_amount DECIMAL(10, 2) NULL,
    tax_percent DECIMAL(5, 2) NULL,
    promo_discount DECIMAL(10, 2) NULL,
    sku VARCHAR(100) NOT NULL,
    quantity INT NOT NULL,
    price DECIMAL(10, 2) NOT NULL,
    subtotal DECIMAL(10, 2) NOT NULL,
    status VARCHAR(50) NOT NULL,
    return_status VARCHAR(50) NULL,
    created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Seller Orders table
CREATE TABLE IF NOT EXISTS seller_orders (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    order_id BIGINT UNSIGNED NOT NULL,
    seller_id BIGINT UNSIGNED NOT NULL,
    store_id BIGINT UNSIGNED NOT NULL,
    subtotal DECIMAL(10, 2) NOT NULL,
    admin_commission DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
    seller_earning DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
    status VARCHAR(50) NOT NULL,
    created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Seller Order Items table
CREATE TABLE IF NOT EXISTS seller_order_items (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    seller_order_id BIGINT UNSIGNED NOT NULL,
    order_item_id BIGINT UNSIGNED NOT NULL,
    created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
