// Generated by diesel - matches exact Laravel database schema
// DO NOT modify field names - they match the original Laravel migrations exactly

diesel::table! {
    users (id) {
        id -> Unsigned<Bigint>,
        #[max_length = 255]
        name -> Varchar,
        #[max_length = 255]
        email -> Varchar,
        email_verified_at -> Nullable<Timestamp>,
        #[max_length = 255]
        password -> Varchar,
        #[max_length = 100]
        remember_token -> Nullable<Varchar>,
        #[max_length = 20]
        mobile -> Varchar,
        #[max_length = 32]
        referral_code -> Nullable<Varchar>,
        #[max_length = 32]
        friends_code -> Nullable<Varchar>,
        reward_points -> Decimal,
        #[max_length = 10]
        status -> Varchar, // 'active', 'inactive'
        #[max_length = 20]
        access_panel -> Nullable<Varchar>, // 'admin', 'seller', 'user'
        #[max_length = 5]
        iso_2 -> Nullable<Varchar>,
        #[max_length = 100]
        country -> Nullable<Varchar>,
        deleted_at -> Nullable<Timestamp>,
        created_at -> Nullable<Timestamp>,
        updated_at -> Nullable<Timestamp>,
    }
}

diesel::table! {
    sessions (id) {
        #[max_length = 255]
        id -> Varchar,
        user_id -> Nullable<Unsigned<Bigint>>,
        #[max_length = 45]
        ip_address -> Nullable<Varchar>,
        user_agent -> Nullable<Text>,
        payload -> Longtext,
        last_activity -> Integer,
    }
}

diesel::table! {
    password_reset_tokens (email) {
        #[max_length = 255]
        email -> Varchar,
        #[max_length = 255]
        token -> Varchar,
        created_at -> Nullable<Timestamp>,
    }
}

diesel::table! {
    roles (id) {
        id -> Unsigned<Bigint>,
        team_id -> Nullable<Unsigned<Bigint>>,
        #[max_length = 255]
        name -> Varchar,
        #[max_length = 255]
        guard_name -> Varchar,
        #[max_length = 100]
        label -> Nullable<Varchar>,
        #[max_length = 255]
        description -> Nullable<Varchar>,
        created_at -> Nullable<Timestamp>,
        updated_at -> Nullable<Timestamp>,
    }
}

diesel::table! {
    permissions (id) {
        id -> Unsigned<Bigint>,
        #[max_length = 255]
        name -> Varchar,
        #[max_length = 255]
        guard_name -> Varchar,
        created_at -> Nullable<Timestamp>,
        updated_at -> Nullable<Timestamp>,
    }
}

diesel::table! {
    role_has_permissions (permission_id, role_id) {
        permission_id -> Unsigned<Bigint>,
        role_id -> Unsigned<Bigint>,
    }
}

diesel::table! {
    model_has_roles (role_id, model_id, model_type) {
        role_id -> Unsigned<Bigint>,
        #[max_length = 255]
        model_type -> Varchar,
        model_id -> Unsigned<Bigint>,
    }
}

diesel::table! {
    model_has_permissions (permission_id, model_id, model_type) {
        permission_id -> Unsigned<Bigint>,
        #[max_length = 255]
        model_type -> Varchar,
        model_id -> Unsigned<Bigint>,
    }
}

diesel::table! {
    categories (id) {
        id -> Unsigned<Bigint>,
        #[max_length = 36]
        uuid -> Varchar,
        parent_id -> Nullable<Unsigned<Bigint>>,
        #[max_length = 255]
        title -> Varchar,
        #[max_length = 255]
        slug -> Varchar,
        #[max_length = 255]
        image -> Varchar,
        #[max_length = 255]
        banner -> Nullable<Varchar>,
        description -> Text,
        #[max_length = 10]
        status -> Varchar, // 'active', 'inactive'
        requires_approval -> Bool,
        commission -> Nullable<Decimal>,
        #[max_length = 20]
        background_type -> Nullable<Varchar>,
        #[max_length = 20]
        background_color -> Nullable<Varchar>,
        #[max_length = 20]
        font_color -> Nullable<Varchar>,
        metadata -> Json,
        deleted_at -> Nullable<Timestamp>,
        created_at -> Nullable<Timestamp>,
        updated_at -> Nullable<Timestamp>,
    }
}

diesel::table! {
    brands (id) {
        id -> Unsigned<Bigint>,
        #[max_length = 36]
        uuid -> Varchar,
        #[max_length = 255]
        slug -> Varchar,
        #[max_length = 255]
        title -> Varchar,
        #[max_length = 255]
        description -> Varchar,
        #[max_length = 255]
        image -> Varchar,
        #[max_length = 255]
        banner -> Nullable<Varchar>,
        #[max_length = 1]
        status -> Varchar, // '0', '1'
        is_featured -> Nullable<Bool>,
        metadata -> Json,
        created_at -> Nullable<Timestamp>,
        updated_at -> Nullable<Timestamp>,
    }
}

diesel::table! {
    product_conditions (id) {
        id -> Unsigned<Bigint>,
        #[max_length = 255]
        title -> Varchar,
        #[max_length = 255]
        slug -> Varchar,
        description -> Nullable<Text>,
        created_at -> Nullable<Timestamp>,
        updated_at -> Nullable<Timestamp>,
    }
}

diesel::table! {
    sellers (id) {
        id -> Unsigned<Bigint>,
        user_id -> Unsigned<Bigint>,
        #[max_length = 255]
        address -> Varchar,
        #[max_length = 100]
        city -> Varchar,
        #[max_length = 100]
        landmark -> Varchar,
        #[max_length = 100]
        state -> Varchar,
        #[max_length = 20]
        zipcode -> Varchar,
        #[max_length = 100]
        country -> Varchar,
        #[max_length = 10]
        country_code -> Varchar,
        latitude -> Nullable<Decimal>,
        longitude -> Nullable<Decimal>,
        business_license -> Text,
        articles_of_incorporation -> Text,
        national_identity_card -> Text,
        authorized_signature -> Text,
        #[max_length = 20]
        verification_status -> Varchar, // 'approved', 'not_approved'
        metadata -> Json,
        #[max_length = 20]
        visibility_status -> Varchar, // 'visible', 'draft'
        deleted_at -> Nullable<Timestamp>,
        created_at -> Nullable<Timestamp>,
        updated_at -> Nullable<Timestamp>,
    }
}

diesel::table! {
    delivery_zones (id) {
        id -> Unsigned<Bigint>,
        #[max_length = 255]
        name -> Varchar,
        #[max_length = 255]
        slug -> Varchar,
        center_latitude -> Decimal,
        center_longitude -> Decimal,
        radius_km -> Double,
        boundary_json -> Nullable<Json>,
        #[max_length = 10]
        status -> Varchar, // 'active', 'inactive'
        delivery_time_per_km -> Nullable<Integer>,
        buffer_time -> Nullable<Integer>,
        min_order_amount -> Nullable<Decimal>,
        delivery_charge_type -> Nullable<Varchar>,
        base_delivery_charge -> Nullable<Decimal>,
        delivery_charge_per_km -> Nullable<Decimal>,
        free_delivery_above -> Nullable<Decimal>,
        per_order_earning -> Nullable<Decimal>,
        per_km_earning -> Nullable<Decimal>,
        base_earning -> Nullable<Decimal>,
        created_at -> Nullable<Timestamp>,
        updated_at -> Nullable<Timestamp>,
    }
}

diesel::table! {
    stores (id) {
        id -> Unsigned<Bigint>,
        seller_id -> Unsigned<Bigint>,
        delivery_zone_id -> Nullable<Unsigned<Bigint>>,
        #[max_length = 255]
        name -> Varchar,
        #[max_length = 300]
        slug -> Varchar,
        #[max_length = 255]
        address -> Varchar,
        #[max_length = 100]
        city -> Varchar,
        #[max_length = 100]
        landmark -> Varchar,
        #[max_length = 100]
        state -> Varchar,
        #[max_length = 20]
        zipcode -> Varchar,
        #[max_length = 100]
        country -> Varchar,
        #[max_length = 10]
        country_code -> Varchar,
        latitude -> Decimal,
        longitude -> Decimal,
        #[max_length = 50]
        contact_email -> Varchar,
        #[max_length = 20]
        contact_number -> Varchar,
        description -> Nullable<Text>,
        #[max_length = 255]
        store_url -> Nullable<Varchar>,
        #[max_length = 500]
        timing -> Nullable<Varchar>,
        address_proof -> Text,
        voided_check -> Text,
        #[max_length = 250]
        tax_name -> Varchar,
        #[max_length = 250]
        tax_number -> Varchar,
        #[max_length = 250]
        bank_name -> Varchar,
        #[max_length = 250]
        bank_branch_code -> Varchar,
        #[max_length = 250]
        account_holder_name -> Varchar,
        #[max_length = 250]
        account_number -> Varchar,
        #[max_length = 250]
        routing_number -> Varchar,
        #[max_length = 20]
        bank_account_type -> Varchar, // 'checking', 'savings'
        #[max_length = 3]
        currency_code -> Varchar,
        permissions -> Nullable<Text>,
        time_slot_config -> Nullable<Json>,
        max_delivery_distance -> Double,
        shipping_min_free_delivery_amount -> Double,
        #[max_length = 255]
        shipping_charge_priority -> Nullable<Varchar>,
        allowed_order_per_time_slot -> Nullable<Integer>,
        order_preparation_time -> Integer,
        carrier_partner -> Nullable<Text>,
        #[max_length = 1024]
        promotional_text -> Nullable<Varchar>,
        about_us -> Text,
        return_replacement_policy -> Nullable<Text>,
        refund_policy -> Nullable<Text>,
        terms_and_conditions -> Nullable<Text>,
        delivery_policy -> Nullable<Text>,
        shipping_preference -> Nullable<Text>,
        domestic_shipping_charges -> Nullable<Decimal>,
        international_shipping_charges -> Nullable<Decimal>,
        metadata -> Json,
        #[max_length = 20]
        verification_status -> Varchar, // 'approved', 'not_approved'
        #[max_length = 20]
        visibility_status -> Varchar, // 'visible', 'draft'
        #[max_length = 20]
        fulfillment_type -> Varchar, // 'hyperlocal', 'regular', 'both'
        #[max_length = 20]
        status -> Nullable<Varchar>,
        deleted_at -> Nullable<Timestamp>,
        created_at -> Nullable<Timestamp>,
        updated_at -> Nullable<Timestamp>,
    }
}

diesel::table! {
    products (id) {
        id -> Unsigned<Bigint>,
        #[max_length = 36]
        uuid -> Varchar,
        seller_id -> Unsigned<Bigint>,
        category_id -> Unsigned<Bigint>,
        brand_id -> Nullable<Unsigned<Bigint>>,
        product_condition_id -> Unsigned<Bigint>,
        #[max_length = 255]
        provider -> Nullable<Varchar>,
        provider_product_id -> Nullable<Unsigned<Bigint>>,
        #[max_length = 500]
        slug -> Varchar,
        #[max_length = 255]
        title -> Varchar,
        product_identity -> Nullable<Integer>,
        #[max_length = 20]
        #[sql_name = "type"]
        product_type -> Varchar, // 'physical', 'digital'
        #[max_length = 255]
        short_description -> Varchar,
        description -> Text,
        #[max_length = 10]
        indicator -> Nullable<Varchar>, // 'veg', 'non_veg'
        #[max_length = 1]
        download_allowed -> Varchar, // '0', '1'
        #[max_length = 255]
        download_link -> Nullable<Varchar>,
        minimum_order_quantity -> Integer,
        quantity_step_size -> Integer,
        total_allowed_quantity -> Integer,
        #[max_length = 1]
        is_inclusive_tax -> Varchar, // '0', '1'
        #[max_length = 50]
        hsn_code -> Nullable<Varchar>,
        #[max_length = 1]
        is_returnable -> Varchar, // '0', '1'
        returnable_days -> Nullable<Integer>,
        #[max_length = 1]
        is_cancelable -> Varchar, // '0', '1'
        #[max_length = 50]
        cancelable_till -> Nullable<Varchar>,
        #[max_length = 1]
        is_attachment_required -> Varchar, // '0', '1'
        base_prep_time -> Nullable<Integer>,
        #[max_length = 20]
        status -> Varchar, // 'active', 'draft'
        #[max_length = 20]
        verification_status -> Nullable<Varchar>,
        rejection_reason -> Nullable<Text>,
        #[max_length = 1]
        featured -> Varchar, // '0', '1'
        requires_otp -> Nullable<Bool>,
        #[max_length = 20]
        video_type -> Nullable<Varchar>, // 'self_hosted', 'youtube', 'vimeo'
        #[max_length = 255]
        video_link -> Nullable<Varchar>,
        cloned_from_id -> Nullable<Unsigned<Bigint>>,
        tags -> Text,
        #[max_length = 255]
        warranty_period -> Nullable<Varchar>,
        #[max_length = 255]
        guarantee_period -> Nullable<Varchar>,
        #[max_length = 255]
        made_in -> Nullable<Varchar>,
        #[max_length = 20]
        image_fit -> Nullable<Varchar>,
        metadata -> Json,
        deleted_at -> Nullable<Timestamp>,
        created_at -> Nullable<Timestamp>,
        updated_at -> Nullable<Timestamp>,
    }
}

diesel::table! {
    product_variants (id) {
        id -> Unsigned<Bigint>,
        #[max_length = 36]
        uuid -> Varchar,
        product_id -> Unsigned<Bigint>,
        #[max_length = 255]
        title -> Varchar,
        #[max_length = 500]
        slug -> Varchar,
        weight -> Float,
        height -> Float,
        breadth -> Float,
        length -> Float,
        availability -> Bool,
        #[max_length = 50]
        provider -> Varchar,
        #[max_length = 255]
        provider_product_id -> Nullable<Varchar>,
        provider_json -> Nullable<Json>,
        #[max_length = 255]
        barcode -> Varchar,
        #[max_length = 20]
        visibility -> Varchar, // 'published', 'draft'
        is_default -> Bool,
        deleted_at -> Nullable<Timestamp>,
        created_at -> Nullable<Timestamp>,
        updated_at -> Nullable<Timestamp>,
    }
}

diesel::table! {
    store_product_variants (id) {
        id -> Unsigned<Bigint>,
        store_id -> Unsigned<Bigint>,
        product_id -> Unsigned<Bigint>,
        product_variant_id -> Unsigned<Bigint>,
        #[max_length = 100]
        sku -> Varchar,
        stock -> Integer,
        price -> Decimal,
        discounted_price -> Nullable<Decimal>,
        created_at -> Nullable<Timestamp>,
        updated_at -> Nullable<Timestamp>,
    }
}

diesel::table! {
    orders (id) {
        id -> Unsigned<Bigint>,
        #[max_length = 36]
        uuid -> Varchar,
        user_id -> Unsigned<Bigint>,
        #[max_length = 100]
        slug -> Varchar,
        #[max_length = 255]
        email -> Varchar,
        #[max_length = 45]
        ip_address -> Varchar,
        #[max_length = 3]
        currency_code -> Varchar,
        currency_rate -> Decimal,
        #[max_length = 50]
        payment_method -> Varchar,
        #[max_length = 50]
        payment_status -> Varchar,
        #[max_length = 20]
        fulfillment_type -> Varchar, // 'hyperlocal', 'regular'
        is_rush_order -> Nullable<Bool>,
        estimated_delivery_time -> Nullable<Integer>,
        delivery_time_slot_id -> Nullable<Unsigned<Bigint>>,
        delivery_boy_id -> Nullable<Unsigned<Bigint>>,
        delivery_zone_id -> Nullable<Unsigned<Bigint>>,
        wallet_balance -> Decimal,
        #[max_length = 50]
        promo_code -> Nullable<Varchar>,
        promo_discount -> Decimal,
        #[max_length = 50]
        gift_card -> Nullable<Varchar>,
        gift_card_discount -> Decimal,
        delivery_charge -> Decimal,
        handling_charges -> Nullable<Decimal>,
        per_store_drop_off_fee -> Nullable<Decimal>,
        subtotal -> Decimal,
        total_payable -> Decimal,
        final_total -> Decimal,
        #[max_length = 50]
        status -> Nullable<Varchar>,
        // Billing Info
        #[max_length = 255]
        billing_name -> Varchar,
        billing_address_1 -> Text,
        billing_address_2 -> Nullable<Text>,
        #[max_length = 255]
        billing_landmark -> Varchar,
        #[max_length = 20]
        billing_zip -> Varchar,
        #[max_length = 20]
        billing_phone -> Varchar,
        #[max_length = 20]
        billing_address_type -> Varchar, // 'home', 'office', 'other'
        billing_latitude -> Decimal,
        billing_longitude -> Decimal,
        #[max_length = 100]
        billing_city -> Varchar,
        #[max_length = 100]
        billing_state -> Varchar,
        #[max_length = 100]
        billing_country -> Varchar,
        #[max_length = 3]
        billing_country_code -> Varchar,
        // Shipping Info
        #[max_length = 255]
        shipping_name -> Varchar,
        shipping_address_1 -> Text,
        shipping_address_2 -> Nullable<Text>,
        #[max_length = 255]
        shipping_landmark -> Varchar,
        #[max_length = 20]
        shipping_zip -> Varchar,
        #[max_length = 20]
        shipping_phone -> Varchar,
        #[max_length = 20]
        shipping_address_type -> Varchar, // 'home', 'office', 'other'
        shipping_latitude -> Decimal,
        shipping_longitude -> Decimal,
        #[max_length = 100]
        shipping_city -> Varchar,
        #[max_length = 100]
        shipping_state -> Varchar,
        #[max_length = 100]
        shipping_country -> Varchar,
        #[max_length = 3]
        shipping_country_code -> Varchar,
        order_note -> Nullable<Text>,
        created_at -> Nullable<Timestamp>,
        updated_at -> Nullable<Timestamp>,
    }
}

diesel::table! {
    order_items (id) {
        id -> Unsigned<Bigint>,
        order_id -> Unsigned<Bigint>,
        product_id -> Unsigned<Bigint>,
        product_variant_id -> Unsigned<Bigint>,
        store_id -> Unsigned<Bigint>,
        #[max_length = 255]
        title -> Varchar,
        #[max_length = 255]
        variant_title -> Varchar,
        gift_card_discount -> Decimal,
        admin_commission_amount -> Decimal,
        seller_commission_amount -> Decimal,
        #[max_length = 1]
        commission_settled -> Varchar, // '0', '1'
        discounted_price -> Decimal,
        discount -> Decimal,
        tax_amount -> Nullable<Decimal>,
        tax_percent -> Nullable<Decimal>,
        promo_discount -> Nullable<Decimal>,
        #[max_length = 100]
        sku -> Varchar,
        quantity -> Integer,
        price -> Decimal,
        subtotal -> Decimal,
        #[max_length = 50]
        status -> Varchar, // 'pending', 'confirmed', 'out_for_delivery', 'delivered', 'canceled'
        #[max_length = 50]
        return_status -> Nullable<Varchar>,
        created_at -> Nullable<Timestamp>,
        updated_at -> Nullable<Timestamp>,
    }
}

diesel::table! {
    seller_orders (id) {
        id -> Unsigned<Bigint>,
        order_id -> Unsigned<Bigint>,
        seller_id -> Unsigned<Bigint>,
        store_id -> Unsigned<Bigint>,
        subtotal -> Decimal,
        admin_commission -> Decimal,
        seller_earning -> Decimal,
        #[max_length = 50]
        status -> Varchar,
        created_at -> Nullable<Timestamp>,
        updated_at -> Nullable<Timestamp>,
    }
}

diesel::table! {
    seller_order_items (id) {
        id -> Unsigned<Bigint>,
        seller_order_id -> Unsigned<Bigint>,
        order_item_id -> Unsigned<Bigint>,
        created_at -> Nullable<Timestamp>,
        updated_at -> Nullable<Timestamp>,
    }
}

diesel::table! {
    delivery_boys (id) {
        id -> Unsigned<Bigint>,
        user_id -> Unsigned<Bigint>,
        delivery_zone_id -> Nullable<Unsigned<Bigint>>,
        #[max_length = 255]
        address -> Varchar,
        #[max_length = 100]
        city -> Varchar,
        #[max_length = 100]
        state -> Varchar,
        #[max_length = 20]
        zipcode -> Varchar,
        #[max_length = 100]
        country -> Varchar,
        national_identity_card -> Text,
        driving_license -> Text,
        vehicle_registration -> Nullable<Text>,
        #[max_length = 255]
        vehicle_number -> Nullable<Varchar>,
        #[max_length = 255]
        vehicle_type -> Nullable<Varchar>,
        #[max_length = 20]
        verification_status -> Varchar, // 'approved', 'not_approved'
        metadata -> Nullable<Json>,
        #[max_length = 20]
        availability_status -> Varchar, // 'available', 'busy', 'offline'
        deleted_at -> Nullable<Timestamp>,
        created_at -> Nullable<Timestamp>,
        updated_at -> Nullable<Timestamp>,
    }
}

diesel::table! {
    delivery_boy_assignments (id) {
        id -> Unsigned<Bigint>,
        order_id -> Unsigned<Bigint>,
        delivery_boy_id -> Unsigned<Bigint>,
        #[max_length = 50]
        status -> Varchar, // 'assigned', 'accepted', 'picked_up', 'delivered', 'canceled'
        accepted_at -> Nullable<Timestamp>,
        picked_up_at -> Nullable<Timestamp>,
        delivered_at -> Nullable<Timestamp>,
        canceled_at -> Nullable<Timestamp>,
        #[max_length = 255]
        cancellation_reason -> Nullable<Varchar>,
        per_order_earning -> Nullable<Decimal>,
        per_km_earning -> Nullable<Decimal>,
        base_earning -> Nullable<Decimal>,
        distance_km -> Nullable<Decimal>,
        total_earning -> Nullable<Decimal>,
        #[max_length = 20]
        payment_status -> Nullable<Varchar>,
        created_at -> Nullable<Timestamp>,
        updated_at -> Nullable<Timestamp>,
    }
}

diesel::table! {
    wallets (id) {
        id -> Unsigned<Bigint>,
        user_id -> Unsigned<Bigint>,
        balance -> Decimal,
        hold_balance -> Nullable<Decimal>,
        created_at -> Nullable<Timestamp>,
        updated_at -> Nullable<Timestamp>,
    }
}

diesel::table! {
    wallet_transactions (id) {
        id -> Unsigned<Bigint>,
        wallet_id -> Unsigned<Bigint>,
        #[max_length = 50]
        transaction_type -> Varchar, // 'credit', 'debit'
        amount -> Decimal,
        balance_after -> Decimal,
        #[max_length = 255]
        description -> Nullable<Varchar>,
        #[max_length = 255]
        reference_type -> Nullable<Varchar>,
        reference_id -> Nullable<Unsigned<Bigint>>,
        metadata -> Nullable<Json>,
        created_at -> Nullable<Timestamp>,
        updated_at -> Nullable<Timestamp>,
    }
}

diesel::table! {
    banners (id) {
        id -> Unsigned<Bigint>,
        #[max_length = 255]
        title -> Varchar,
        #[max_length = 255]
        image -> Varchar,
        #[max_length = 50]
        link_type -> Nullable<Varchar>,
        #[max_length = 500]
        link_value -> Nullable<Varchar>,
        #[max_length = 50]
        position -> Nullable<Varchar>,
        sort_order -> Nullable<Integer>,
        #[max_length = 10]
        status -> Varchar, // 'active', 'inactive'
        start_date -> Nullable<Timestamp>,
        end_date -> Nullable<Timestamp>,
        created_at -> Nullable<Timestamp>,
        updated_at -> Nullable<Timestamp>,
    }
}

diesel::table! {
    featured_sections (id) {
        id -> Unsigned<Bigint>,
        #[max_length = 36]
        uuid -> Varchar,
        #[max_length = 255]
        title -> Varchar,
        #[max_length = 255]
        subtitle -> Nullable<Varchar>,
        #[max_length = 50]
        section_type -> Varchar,
        #[max_length = 50]
        layout_type -> Nullable<Varchar>,
        #[max_length = 50]
        product_filter -> Nullable<Varchar>,
        product_limit -> Nullable<Integer>,
        sort_order -> Nullable<Integer>,
        #[max_length = 10]
        status -> Varchar,
        metadata -> Nullable<Json>,
        created_at -> Nullable<Timestamp>,
        updated_at -> Nullable<Timestamp>,
    }
}

diesel::table! {
    promos (id) {
        id -> Unsigned<Bigint>,
        #[max_length = 50]
        code -> Varchar,
        #[max_length = 255]
        title -> Varchar,
        description -> Nullable<Text>,
        #[max_length = 50]
        discount_type -> Varchar, // 'percentage', 'fixed'
        discount_value -> Decimal,
        min_order_amount -> Nullable<Decimal>,
        max_discount_amount -> Nullable<Decimal>,
        usage_limit -> Nullable<Integer>,
        usage_limit_per_user -> Nullable<Integer>,
        times_used -> Integer,
        start_date -> Nullable<Timestamp>,
        end_date -> Nullable<Timestamp>,
        #[max_length = 10]
        status -> Varchar, // 'active', 'inactive'
        created_at -> Nullable<Timestamp>,
        updated_at -> Nullable<Timestamp>,
    }
}

diesel::table! {
    settings (id) {
        id -> Unsigned<Bigint>,
        #[max_length = 100]
        variable -> Varchar,
        value -> Nullable<Longtext>,
        created_at -> Nullable<Timestamp>,
        updated_at -> Nullable<Timestamp>,
    }
}

diesel::table! {
    tax_classes (id) {
        id -> Unsigned<Bigint>,
        #[max_length = 255]
        name -> Varchar,
        #[max_length = 255]
        slug -> Varchar,
        description -> Nullable<Text>,
        is_default -> Bool,
        created_at -> Nullable<Timestamp>,
        updated_at -> Nullable<Timestamp>,
    }
}

diesel::table! {
    tax_rates (id) {
        id -> Unsigned<Bigint>,
        #[max_length = 255]
        name -> Varchar,
        rate -> Decimal,
        #[max_length = 100]
        country -> Nullable<Varchar>,
        #[max_length = 100]
        state -> Nullable<Varchar>,
        #[max_length = 20]
        zip -> Nullable<Varchar>,
        priority -> Integer,
        compound -> Bool,
        created_at -> Nullable<Timestamp>,
        updated_at -> Nullable<Timestamp>,
    }
}

diesel::table! {
    faqs (id) {
        id -> Unsigned<Bigint>,
        #[max_length = 500]
        question -> Varchar,
        answer -> Text,
        sort_order -> Nullable<Integer>,
        #[max_length = 10]
        status -> Varchar, // 'active', 'inactive'
        created_at -> Nullable<Timestamp>,
        updated_at -> Nullable<Timestamp>,
    }
}

diesel::table! {
    reviews (id) {
        id -> Unsigned<Bigint>,
        user_id -> Unsigned<Bigint>,
        product_id -> Unsigned<Bigint>,
        order_id -> Nullable<Unsigned<Bigint>>,
        order_item_id -> Nullable<Unsigned<Bigint>>,
        rating -> Integer,
        comment -> Nullable<Text>,
        #[max_length = 20]
        status -> Varchar, // 'pending', 'approved', 'rejected'
        created_at -> Nullable<Timestamp>,
        updated_at -> Nullable<Timestamp>,
    }
}

diesel::table! {
    support_ticket_types (id) {
        id -> Unsigned<Bigint>,
        #[max_length = 255]
        title -> Varchar,
        #[max_length = 255]
        slug -> Varchar,
        description -> Nullable<Text>,
        #[max_length = 10]
        status -> Varchar,
        created_at -> Nullable<Timestamp>,
        updated_at -> Nullable<Timestamp>,
    }
}

diesel::table! {
    support_tickets (id) {
        id -> Unsigned<Bigint>,
        user_id -> Unsigned<Bigint>,
        ticket_type_id -> Unsigned<Bigint>,
        #[max_length = 50]
        ticket_number -> Varchar,
        #[max_length = 255]
        subject -> Varchar,
        #[max_length = 50]
        priority -> Varchar, // 'low', 'medium', 'high', 'urgent'
        #[max_length = 50]
        status -> Varchar, // 'open', 'in_progress', 'resolved', 'closed'
        created_at -> Nullable<Timestamp>,
        updated_at -> Nullable<Timestamp>,
    }
}

diesel::table! {
    support_ticket_messages (id) {
        id -> Unsigned<Bigint>,
        ticket_id -> Unsigned<Bigint>,
        user_id -> Unsigned<Bigint>,
        message -> Text,
        is_admin_reply -> Bool,
        created_at -> Nullable<Timestamp>,
        updated_at -> Nullable<Timestamp>,
    }
}

diesel::table! {
    notifications (id) {
        id -> Unsigned<Bigint>,
        #[max_length = 255]
        title -> Varchar,
        message -> Text,
        #[max_length = 50]
        notification_type -> Varchar,
        #[max_length = 255]
        target_type -> Nullable<Varchar>,
        target_id -> Nullable<Unsigned<Bigint>>,
        data -> Nullable<Json>,
        read_at -> Nullable<Timestamp>,
        created_at -> Nullable<Timestamp>,
        updated_at -> Nullable<Timestamp>,
    }
}

diesel::table! {
    countries (id) {
        id -> Unsigned<Bigint>,
        #[max_length = 100]
        name -> Varchar,
        #[max_length = 5]
        iso_2 -> Varchar,
        #[max_length = 5]
        iso_3 -> Varchar,
        #[max_length = 10]
        phone_code -> Varchar,
        #[max_length = 10]
        currency_code -> Varchar,
        #[max_length = 50]
        currency_name -> Varchar,
        #[max_length = 10]
        currency_symbol -> Varchar,
        created_at -> Nullable<Timestamp>,
        updated_at -> Nullable<Timestamp>,
    }
}

// Define all table relationships
// diesel::joinable!(sellers -> users (user_id));
// diesel::joinable!(stores -> sellers (seller_id));
// diesel::joinable!(stores -> delivery_zones (delivery_zone_id));
// diesel::joinable!(products -> sellers (seller_id));
// diesel::joinable!(products -> categories (category_id));
// diesel::joinable!(products -> brands (brand_id));
// diesel::joinable!(products -> product_conditions (product_condition_id));
// diesel::joinable!(product_variants -> products (product_id));
// diesel::joinable!(store_product_variants -> stores (store_id));
// diesel::joinable!(store_product_variants -> products (product_id));
// diesel::joinable!(store_product_variants -> product_variants (product_variant_id));
// diesel::joinable!(orders -> users (user_id));
// diesel::joinable!(order_items -> orders (order_id));
// diesel::joinable!(order_items -> products (product_id));
// diesel::joinable!(order_items -> product_variants (product_variant_id));
// diesel::joinable!(order_items -> stores (store_id));
// diesel::joinable!(seller_orders -> orders (order_id));
// diesel::joinable!(seller_orders -> sellers (seller_id));
// diesel::joinable!(seller_orders -> stores (store_id));
// diesel::joinable!(delivery_boys -> users (user_id));
// diesel::joinable!(delivery_boys -> delivery_zones (delivery_zone_id));
// diesel::joinable!(delivery_boy_assignments -> orders (order_id));
// diesel::joinable!(delivery_boy_assignments -> delivery_boys (delivery_boy_id));
// diesel::joinable!(wallets -> users (user_id));
// diesel::joinable!(wallet_transactions -> wallets (wallet_id));
// diesel::joinable!(reviews -> users (user_id));
// diesel::joinable!(reviews -> products (product_id));
// diesel::joinable!(reviews -> orders (order_id));
// diesel::joinable!(support_tickets -> users (user_id));
// diesel::joinable!(support_tickets -> support_ticket_types (ticket_type_id));
// diesel::joinable!(support_ticket_messages -> support_tickets (ticket_id));
// diesel::joinable!(support_ticket_messages -> users (user_id));
// diesel::joinable!(role_has_permissions -> roles (role_id));
// diesel::joinable!(role_has_permissions -> permissions (permission_id));
// diesel::joinable!(categories -> categories (parent_id));

diesel::allow_tables_to_appear_in_same_query!(
    users,
    sessions,
    password_reset_tokens,
    roles,
    permissions,
    role_has_permissions,
    model_has_roles,
    model_has_permissions,
    categories,
    brands,
    product_conditions,
    sellers,
    delivery_zones,
    stores,
    products,
    product_variants,
    store_product_variants,
    orders,
    order_items,
    seller_orders,
    seller_order_items,
    delivery_boys,
    delivery_boy_assignments,
    wallets,
    wallet_transactions,
    banners,
    featured_sections,
    promos,
    settings,
    tax_classes,
    tax_rates,
    faqs,
    reviews,
    support_ticket_types,
    support_tickets,
    support_ticket_messages,
    notifications,
    countries,
);
