// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXt0MyoIMDglAT26pgOfV0uYdqRlVp6JY',
    appId: '1:934594751104:android:c7d4daab18216be0715465',
    messagingSenderId: '934594751104',
    projectId: 'optimal-doodad-397604',
    storageBucket: 'optimal-doodad-397604.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcRrHG0A1Zbk-3d1gcDF2wnbwSTIrrd_o',
    appId: '1:934594751104:ios:24800d84f8a9f91a715465',
    messagingSenderId: '934594751104',
    projectId: 'optimal-doodad-397604',
    storageBucket: 'optimal-doodad-397604.firebasestorage.app',
    androidClientId: '934594751104-4ql80ffrbja2g87a4162si5vsni4noc2.apps.googleusercontent.com',
    iosClientId: '934594751104-d61k970ola4qp0b33s058jv3ch52hkge.apps.googleusercontent.com',
    iosBundleId: 'com.hyperLocal.customer',
  );

}